name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 22f3001777@ds.study.iitm.ac.in
        run: echo "Hello, world!"
